workflows:
  ios-build:
    name: Voxu iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: .
    labels:
      - capacitor

    integrations:
      app_store_connect: app_store_connect

    environment:
      node: 22
      xcode: 16.2
      groups:
        - app_store_connect
      vars:
        BUNDLE_ID: com.voxu.app
        APP_STORE_APPLE_ID: "6759702163"

    cache:
      cache_paths:
        - $HOME/.npm

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Capacitor sync
        script: npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          # Fetch existing profiles (don't create new API-based ones)
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE
          keychain add-certificates
          xcode-project use-profiles

      - name: Set version and build number
        script: |
          cd ios/App
          agvtool new-marketing-version 1.0.0
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0) + 1))

      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=FX8T7ASYCL \
            PROVISIONING_PROFILE_SPECIFIER="Voxu App Store Distribution" \
            archive

      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/export

    artifacts:
      - ios/App/build/export/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
