workflows:
  ios-build:
    name: Voxu iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: .
    labels:
      - capacitor

    integrations:
      app_store_connect: app_store_connect

    environment:
      node: 22
      xcode: 16.2
      groups:
        - app_store_connect
      vars:
        BUNDLE_ID: com.voxu.app
        APP_STORE_APPLE_ID: "6759702163"

    cache:
      cache_paths:
        - $HOME/.npm

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Capacitor sync
        script: npx cap sync ios

      - name: Install Apple Certificate
        script: |
          CERTIFICATE_PATH=/tmp/build_certificate.p12
          KEYCHAIN_PATH=/tmp/app-signing.keychain-db
          KEYCHAIN_PASSWORD=$(openssl rand -base64 32)

          # Decode certificate from base64 env var
          echo -n "$IOS_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P "$IOS_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          echo "=== Installed certificates ==="
          security find-identity -v -p codesigning $KEYCHAIN_PATH

      - name: Install Provisioning Profile
        script: |
          PP_PATH=/tmp/build_pp.mobileprovision

          # Decode provisioning profile from base64 env var
          echo -n "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > $PP_PATH

          # Extract UUID from provisioning profile
          PP_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i $PP_PATH))
          echo "Provisioning Profile UUID: $PP_UUID"

          # Install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/$PP_UUID.mobileprovision

          # Extract and show profile name
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i $PP_PATH))
          echo "Profile name: $PROFILE_NAME"

      - name: Set version and build number
        script: |
          cd ios/App
          agvtool new-marketing-version 1.0.0
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0) + 1))

      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            archive

      - name: Generate ExportOptions and export IPA
        script: |
          cd ios/App
          PROFILE_PATH=$(find "$HOME/Library/MobileDevice/Provisioning Profiles" -name "*.mobileprovision" -type f 2>/dev/null | head -1)
          if [ -z "$PROFILE_PATH" ]; then
            echo "ERROR: No provisioning profile found!"
            exit 1
          fi
          PROFILE_NAME=$(security cms -D -i "$PROFILE_PATH" | plutil -extract Name raw -)
          echo "Using profile: $PROFILE_NAME"
          /usr/libexec/PlistBuddy -c "Clear dict" ExportOptions.plist 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :method string app-store" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :teamID string FX8T7ASYCL" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :signingStyle string manual" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :signingCertificate string 'Apple Distribution'" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles dict" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:com.voxu.app string '$PROFILE_NAME'" ExportOptions.plist
          echo "=== ExportOptions.plist ==="
          cat ExportOptions.plist
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/export

      - name: Cleanup Keychain
        script: security delete-keychain /tmp/app-signing.keychain-db || true

    artifacts:
      - ios/App/build/export/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
