/**
 * The daily mission bank for each era: one concrete, single-day action per day,
 * shown on the home card as "Today's mission" (tapping it uses it as the promise).
 *
 * Index 0 is day 1. Every list has exactly 30 entries, in four stages:
 *   days 1–7   Starting    — small, easy wins and setup
 *   days 8–14  Building    — a bit more
 *   days 15–21 Maintaining — consistency, handling the dip
 *   days 22–30 Becoming    — identity, harder, reflecting on the change
 * Day 30 is always a reflective finale.
 *
 * Keys must match ERA_PRESETS in lib/era/presets.ts, plus 'custom' (which must
 * not assume a topic, since the user names that era themselves). Missions stay
 * under 70 characters, with no trailing period.
 */
export const ERA_MISSIONS: Record<string, readonly string[]> = {
  locked_in: [
    // Starting (days 1–7)
    'Write down the one task that would move your life forward most',
    'Put your phone in another room for your first hour of work',
    "Clear your desk of everything you won't use today",
    'Block 45 minutes on your calendar and protect it',
    "Close every tab that has nothing to do with today's work",
    'Turn off every non-essential notification for the day',
    "Finish one small task you've put off for over a week",
    // Building (days 8–14)
    'Give your most important task 90 minutes before anything else',
    'Say no to one request that pulls you away from what matters',
    'Work in two 50-minute blocks with a real break between them',
    'Batch all your messages into two set times today',
    "Write tomorrow's top three tasks before you stop tonight",
    'Delete or mute one app that keeps pulling you off track',
    'List what moved forward this week and what drifted',
    // Maintaining (days 15–21)
    'Start your hardest task within 10 minutes of sitting down',
    'Each time you drift today, jot down what pulled you away',
    "Cut out yesterday's biggest distraction for the whole day",
    'Do one focused block today, even if it feels flat',
    'Finish something today instead of starting something new',
    'Spend 20 minutes planning the next week of real work',
    'Keep your phone out of reach until your main task is done',
    // Becoming (days 22–30)
    'Do a three-hour deep work stretch with only short breaks',
    "Tackle the task you've been avoiding the longest",
    'Tell someone what you are working on and when it will be done',
    'Go a full workday without opening social media',
    'Drop one recurring commitment that no longer earns its time',
    "Ship something today, even if it isn't perfect",
    'Write the rules you now work by, in five lines or fewer',
    "Lock in tomorrow's first hour before you go to sleep",
    'Reread what you wanted to change on day 1 and write what shifted',
  ],
  discipline: [
    // Starting (days 1–7)
    'Pick one small daily task and do it at a set time today',
    'Make your bed as soon as you get up',
    'Wash the dishes right after you eat, not later',
    'Write the one thing you will do today, then do it first',
    'Set a 10-minute timer and start the task you keep dodging',
    'Keep one promise to yourself before noon',
    "Set out tomorrow's clothes and bag before bed",
    // Building (days 8–14)
    'Do your main task today, even with zero urge to',
    'Skip one small comfort today and sit with the urge',
    'Finish a task completely before you allow yourself a break',
    'Get up the first time your alarm goes off',
    "Clear the boring admin task you've been leaving for later",
    'Swap five minutes of scrolling for five minutes of the work',
    'Write down three times this week you acted without motivation',
    // Maintaining (days 15–21)
    'Do your task at the planned time, not when you feel like it',
    'Keep going for five more minutes when you want to stop',
    'Write out your plan for the day and follow it to the letter',
    'On a low day, do the smallest version of your task, but do it',
    'Go the whole day without putting a single task off',
    "Tidy one space you've been ignoring for weeks",
    'Hold your routine even if your schedule gets thrown off',
    // Becoming (days 22–30)
    'Do the hardest thing on your list before anything else',
    'Keep every commitment you make today, however small',
    'Restart one habit you quit before, starting today',
    'Do your task quietly, without talking or posting about it',
    'Stay with one hard task for a full hour without switching',
    'Plan tomorrow tonight and set out everything you will need',
    'Write the excuse you use most, and your answer to it',
    'Give your daily task your best effort, not just enough',
    'Look back on 30 days and write what you did without motivation',
  ],
  comeback: [
    // Starting (days 1–7)
    'Write one sentence about where you are right now, no judgment',
    'Open a window and drink a glass of water when you wake up',
    'Take a 10-minute walk outside at whatever pace feels okay',
    'Tidy one small corner of your space',
    "Send a short message to someone you've missed",
    'Go to bed 20 minutes earlier than last night',
    'Write down one thing you handled better than you expected',
    // Building (days 8–14)
    'Pick a routine you used to love and give it five minutes',
    'Eat one meal sitting down, without a screen',
    'Spend 20 minutes on something that used to feel like you',
    'Write down three things that still work in your life',
    "Clear one small task that's been hanging over you",
    'Step outside in daylight for at least 15 minutes',
    'Tell one person you trust how you are really doing',
    // Maintaining (days 15–21)
    'Keep one small routine going today, even on a heavy day',
    'If today is hard, take the smallest step and call it enough',
    "Write what you'd tell a friend in your spot, then read it",
    "Set down one thing you're not ready to carry right now",
    'Plan one thing to look forward to this week',
    'Rest on purpose today: pick a time and actually take it',
    'Notice one way you are steadier than three weeks ago',
    // Becoming (days 22–30)
    'Take one real step toward a goal you had before things got hard',
    'Return to one place or habit that made you feel strong',
    'Write down what this hard stretch taught you, if anything',
    'Ask for help with one thing instead of carrying it alone',
    'Set one gentle goal for next month and write it down',
    'Do one thing today that past you would be proud of',
    'Write a short note to yourself for the next hard day',
    'Say no to one thing that would drain what you have rebuilt',
    'Reread your day 1 sentence and write how far you have come',
  ],
  gym_arc: [
    // Starting (days 1–7)
    'Pick three days this week to train and put them in your calendar',
    'Take a 20-minute walk at an easy pace',
    'Pack your gym bag tonight and leave it by the door',
    'Do 10 minutes of gentle stretching before bed',
    'Do a short full-body session and stop well before you are spent',
    'Rest day: take an easy walk and let your body recover',
    'Write down what you want your body to be able to do',
    // Building (days 8–14)
    'Warm up properly for 10 minutes before you train today',
    'Learn the correct form for one lift from a trusted source',
    'Add one set to an exercise that felt easy last time',
    'Do 15 minutes of mobility work for your hips and shoulders',
    "Log every exercise, set and rep from today's session",
    'Rest day: stretch lightly and get to bed on time',
    'Try a new kind of movement for 20 minutes, like a bike or a hike',
    // Maintaining (days 15–21)
    "Train today, even if it's a short session",
    'Stop any exercise that causes sharp pain and swap it out',
    'Walk for 30 minutes at a time you would usually sit',
    'Train slow and controlled today, focused on form, not load',
    'Recovery day: 20 minutes of mobility and an early night',
    'Fill your water bottle and keep it with you all day',
    'On a low-energy day, train lighter and still count it',
    // Becoming (days 22–30)
    'Beat one number in your log by a small, safe margin',
    "Plan next week's sessions around the days you actually have",
    'Hold a plank with good form and write down your time',
    'Full rest day: no training, just a walk and a good night of sleep',
    'Invite a friend to train or walk with you',
    'Do the session you used to skip most often',
    "Try a movement you couldn't do on day 1, with good form",
    'Stretch for 15 minutes and notice what feels different now',
    'Compare your log to day 1 and write what your body can do now',
  ],
  stoic_mode: [
    // Starting (days 1–7)
    "Write one thing in your control today and one that isn't",
    'Read a short passage from a Stoic and copy out one line',
    'Before bed, write what you did well and what to do better',
    'When something annoys you, take three breaths before you respond',
    'Picture one thing that could go wrong today, and your calm reply',
    'Let one small inconvenience pass without comment',
    'End the day with three lines on how you responded to it',
    // Building (days 8–14)
    'Take the stairs or walk instead of the easy option once today',
    'Skip one small comfort today, like music on your commute',
    'Name one worry and sort it: act on it, or let it go',
    'Wait an hour before replying to one frustrating message',
    "Spend 10 minutes imagining life without something you'd miss",
    'Do one kind thing for someone who has irritated you',
    'Review the week: where did you react, and where did you choose?',
    // Maintaining (days 15–21)
    'Go a full day without complaining out loud',
    'When plans fall apart today, ask what is still yours to do',
    'Leave your phone out of the bedroom tonight',
    'Take one piece of criticism today without defending yourself',
    'Write down a loss you fear, then how you would carry on',
    'Let someone else be right today without correcting them',
    'Before reacting to bad news, write what you can still control',
    // Becoming (days 22–30)
    'Spend an hour with no input at all: no phone, no music',
    'Do your work well today with no need for credit',
    'Reflect for five minutes on how short life is, then act',
    'Forgive one old grudge in writing, even if you never send it',
    'Stay calm in one moment where you would usually snap',
    'Picture this week from ten years out and write what still matters',
    'Write your own rule for handling what you cannot control',
    'Judge actions today, not people, and that includes yourself',
    'Look back on 30 days: what no longer rules you that once did?',
  ],
  confidence: [
    // Starting (days 1–7)
    'Make eye contact and say hello to one person today',
    'Stand tall with your shoulders back for your whole commute',
    'Write down three things you are genuinely good at',
    'Ask for exactly what you want once today, without apologizing',
    'Ask one question in a meeting, class or conversation',
    'Wear something that makes you feel most like yourself',
    'Speak a little slower and louder than usual in one conversation',
    // Building (days 8–14)
    'Share your opinion once today before anyone asks for it',
    'Give someone a direct, specific compliment',
    "Say no to one thing you don't want to do, without a long excuse",
    "Start a conversation with someone you don't know well",
    'Record yourself talking for one minute and listen back once',
    'Take a seat near the front instead of the back',
    'Accept a compliment with a simple thank you, nothing more',
    // Maintaining (days 15–21)
    'Be the first to speak up in one group conversation today',
    'Respectfully disagree with someone once today',
    'Ask someone for honest feedback on something you made',
    'Show one piece of your work to someone whose opinion you value',
    'Catch one put-down you say about yourself and rewrite it',
    'Ask for help with something instead of struggling quietly',
    'Hold a pause in conversation without rushing to fill it',
    // Becoming (days 22–30)
    'Ask for something you want: a chance, a favor, a raise',
    "Introduce yourself to someone you've wanted to meet",
    'Lead one thing today: a plan, a meeting or a decision',
    "Say the thing you'd usually keep to yourself",
    'Tell someone about one of your goals, out loud',
    'Do one thing you avoided because of what people might think',
    'Walk into a room today and greet people first',
    'Write about a moment this month when you took up space',
    'Write a note to your day 1 self about who you are now',
  ],
  study: [
    // Starting (days 1–7)
    'Set up one clean, quiet spot that is only for studying',
    'Write down what you are studying for and why it matters',
    'Do one 25-minute session with your phone out of sight',
    'Make a simple study schedule for the next seven days',
    "Summarize today's material in five lines from memory",
    'Gather all your materials before you sit down to study',
    'Do two 25-minute sessions with a short break in between',
    // Building (days 8–14)
    "Quiz yourself on yesterday's material before reading anything new",
    'Study for 60 minutes straight with notifications off',
    'Explain one concept out loud as if teaching a friend',
    "Write 10 flashcards or questions from today's topic",
    'Work through practice problems instead of rereading notes',
    'Spend 30 minutes on the topic you understand least',
    'Review the whole week in one sitting and mark your weak spots',
    // Maintaining (days 15–21)
    "Study at your planned time, even if you're not in the mood",
    'Do a 90-minute deep work block with one short break',
    'Revisit week one material and test what you still know',
    'Do one full session with no music or background noise',
    "Write a page linking today's topic to something you already know",
    "Ask a teacher, classmate or forum about one thing you're stuck on",
    'Keep your phone in another room for your whole study time',
    // Becoming (days 22–30)
    'Take a full timed practice test under real conditions',
    'Teach a topic to someone, or record yourself explaining it',
    'Complete two deep work blocks of at least 90 minutes each',
    'Rewrite your weakest notes into a clear one-page summary',
    'Study for 30 minutes before you open any other app today',
    'Go back to your hardest topic and prove you can do it now',
    'Plan how you will keep studying after this era ends',
    'Put a long session into the goal you wrote down on day 2',
    "Write what you know now that you didn't know 30 days ago",
  ],
  five_am: [
    // Starting (days 1–7)
    'Set your alarm 15 minutes earlier than usual',
    'Charge your phone outside your bedroom tonight',
    'Pick a bedtime that gives you enough sleep and set a reminder',
    'Lay out your clothes and plan your first 30 minutes tonight',
    'Drink a glass of water and open the curtains right after waking',
    'Stay off your phone for the first 15 minutes after waking',
    'Move your alarm 15 minutes earlier, and your bedtime with it',
    // Building (days 8–14)
    'Spend your first quiet 20 minutes on something that matters',
    'Get 10 minutes of morning light outside or by a window',
    'Keep screens off for the last 30 minutes before bed',
    'Write three things you want from your morning, then do one',
    'Do 10 minutes of light movement or stretching after you wake',
    'Get up when the alarm rings, no snooze',
    'Count the mornings you owned this week and note what helped',
    // Maintaining (days 15–21)
    'Wake at your target time and protect the first hour',
    'Start winding down 45 minutes before your set bedtime',
    'Use your first hour for the most important work of the day',
    'Read 15 pages of a book before you check any messages',
    'On a rough morning, keep just the wake time and one small habit',
    'Plan tomorrow morning in detail before you go to bed',
    'Stay off your phone for the first 45 minutes after waking',
    // Becoming (days 22–30)
    'Keep your wake time on a day off too',
    'Write for 15 minutes about what you want this year to hold',
    'Finish your hardest task of the day before 8 AM',
    'Take a quiet walk before the world wakes up',
    'Protect your bedtime tonight, even if something fun comes up',
    'Run your whole morning routine with zero screens',
    'Watch the sky get light, with no phone in your hand',
    'Write down what the early hours have given you so far',
    'Look back on 30 mornings and write what owning them changed',
  ],
  custom: [
    // Starting (days 1–7)
    'Write down in one sentence what this era is for',
    'Pick one small action toward your goal and do it today',
    'Remove one thing from your space that works against your goal',
    'Spend 15 minutes on your goal before anything else',
    'Tell one person you trust what you are working on',
    'Write down what a good day in this era looks like',
    'Notice one thing that has already shifted and write it down',
    // Building (days 8–14)
    'Spend 30 minutes on your goal with no distractions',
    "Do the part of your goal you've been avoiding",
    'Set a fixed time for your goal tomorrow and put it in your calendar',
    'Learn one thing today that helps you with your goal',
    'Say no to one thing that pulls you away from this era',
    'Write what makes the hard days hard, and one fix for it',
    'Look back at the week and choose one thing to do differently',
    // Maintaining (days 15–21)
    'Show up for your goal today, even if only for 10 minutes',
    'On a slow day, take the smallest possible step and count it',
    'Write why this era matters to you, in your own words',
    'Do one thing for your goal that nobody will see',
    'Ask someone for advice or support on your goal',
    'Rest on purpose today, then pick it back up tomorrow',
    'Reread your day 1 sentence and take one step with it in mind',
    // Becoming (days 22–30)
    "Take a bigger step than you've tried so far",
    'Act today the way the person you are becoming would act',
    'Give your goal one full hour in a single focused stretch',
    'Drop one old habit that belongs to who you were before',
    "Help someone with something you've learned this era",
    'Write the three most useful things this era has taught you',
    'Plan how you will keep this going after day 30',
    'Do the thing today that felt out of reach on day 1',
    'Write a letter to your day 1 self about what has changed',
  ],
}
